In [1]:
import pandas as pd
import numpy as np

In [2]:
train_data = pd.read_csv("train.csv")

In [3]:
train_data.head()

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,PRODUCT_LENGTH
0,1925202,ArtzFolio Tulip Flowers Blackout Curtain for D...,[LUXURIOUS & APPEALING: Beautiful custom-made ...,NaN,1650,2125.980000
1,2673191,Marks & Spencer Girls' Pyjama Sets T86_2561C_N...,"[Harry Potter Hedwig Pyjamas (6-16 Yrs),100% c...",NaN,2755,393.700000
2,2765088,PRIKNIK Horn Red Electric Air Horn Compressor ...,"[Loud Dual Tone Trumpet Horn, Compatible With ...","Specifications: Color: Red, Material: Aluminiu...",7537,748.031495
3,1594019,ALISHAH Women's Cotton Ankle Length Leggings C...,[Made By 95%cotton and 5% Lycra which gives yo...,AISHAH Women's Lycra Cotton Ankel Leggings. Br...,2996,787.401574
4,283658,The United Empire Loyalists: A Chronicle of th...,NaN,NaN,6112,598.424000

In [4]:
train_data.shape
#we have over 2 million data

(2249698, 6)

In [5]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2249698 entries, 0 to 2249697
Data columns (total 6 columns):
 #   Column           Dtype
---  ------           -----
 0   PRODUCT_ID       int64
 1   TITLE            object
 2   BULLET_POINTS    object
 3   DESCRIPTION      object
 4   PRODUCT_TYPE_ID  int64
 5   PRODUCT_LENGTH   float64
dtypes: float64(1), int64(2), object(3)
memory usage: 103.0+ MB

In [6]:
#create a backup
backup = train_data

In [7]:
#FIRST TASK IS TO CLEAN THE DESCRIPTION AND BULLET POINTS COLUMNS AND JOIN THEM

#TITLE
train_data[train_data["TITLE"].isna() == True ]

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,PRODUCT_LENGTH
66157,1804,NaN,NaN,NaN,222,507.873000
196485,164542,NaN,NaN,NaN,150,575.000000
420890,16935,NaN,NaN,NaN,6104,290.000000
477469,1362139,NaN,[Top-notch and innovative tremolo pedal offers...,NaN,6632,500.000000
948754,566503,NaN,NaN,NaN,109,555.117000
1144461,678966,NaN,NaN,NaN,1,685.038000
1364032,548186,NaN,NaN,NaN,1,1228.344000
1716822,20369,NaN,NaN,NaN,154,1040.000000
1879925,496531,NaN,NaN,NaN,1,799.211000
1885213,555363,NaN,NaN,NaN,151,846.455000
1937873,1401496,NaN,[PACKAGE CONTENT: 6 Table Mats & 6 Coasters | ...,NaN,1346,1181.102361
2108453,113675,NaN,NaN,NaN,6044,600.000000

In [8]:
#Drop these
train_data = train_data.dropna(subset=["TITLE"])

In [9]:
#check for NULL in description and bullet points both

duplicate_desc = train_data["DESCRIPTION"].isna()
duplicate_bullet = train_data["BULLET_POINTS"].isna()
both_duplicate = duplicate_bullet & duplicate_desc
train_data[both_duplicate]

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,PRODUCT_LENGTH
4,283658,The United Empire Loyalists: A Chronicle of th...,NaN,NaN,6112,598.424
6,413758,Ungifted: My Life and Journey,NaN,NaN,23,598.000
11,833712,La Mure / Valbonnais gps,NaN,NaN,1,433.070
12,648364,J'ecris des lettres! premiers exercices d'écri...,NaN,NaN,1,759.841
13,1991694,Mediterranean diet for beginners: 7Benefits of...,NaN,NaN,32,600.000
...,...,...,...,...,...,...
2249679,111250,When Work Becomes Optional,NaN,NaN,87,600.000
2249681,421168,Learning to Swim,NaN,NaN,12743,525.000
2249682,38572,"Holy Bible: New International Version, Camel/c...",NaN,NaN,129,488.188
2249691,571566,Comedy Wildlife Photography Awards: The perfec...,NaN,NaN,2968,271.250
2249696,1165754,Electro Voice EKX-BRKT15 | Wall Mount Bracket ...,NaN,NaN,592,2900.000

In [10]:
#dropping these
train_data = train_data.dropna(subset=['DESCRIPTION', 'BULLET_POINTS'], how='all')

In [11]:
train_data.shape

(1466189, 6)

In [12]:
train_data = train_data.reset_index(drop=True)

In [13]:
train_data

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,PRODUCT_LENGTH
0,1925202,ArtzFolio Tulip Flowers Blackout Curtain for D...,[LUXURIOUS & APPEALING: Beautiful custom-made ...,NaN,1650,2125.980000
1,2673191,Marks & Spencer Girls' Pyjama Sets T86_2561C_N...,"[Harry Potter Hedwig Pyjamas (6-16 Yrs),100% c...",NaN,2755,393.700000
2,2765088,PRIKNIK Horn Red Electric Air Horn Compressor ...,"[Loud Dual Tone Trumpet Horn, Compatible With ...","Specifications: Color: Red, Material: Aluminiu...",7537,748.031495
3,1594019,ALISHAH Women's Cotton Ankle Length Leggings C...,[Made By 95%cotton and 5% Lycra which gives yo...,AISHAH Women's Lycra Cotton Ankel Leggings. Br...,2996,787.401574
4,2152929,HINS Metal Bucket Shape Plant Pot for Indoor &...,"[Simple and elegant, great for displaying indo...",HINS Brings you the most Elegant Looking Pot w...,5725,950.000000
...,...,...,...,...,...,...
1466184,2690647,Olmeo 14 LED Round Fog Light 4 Inches Waterpro...,"[Easy to install;,Round shape 14LED spot worki...",NaN,7978,590.550000
1466185,2422167,Nike Women's As W Ny Df Swsh Hn Kh Bra (CZ7610...,Material : Polyester,NaN,3009,1181.100000
1466186,2766635,"(3PCS) Goose Game Cute Cartoon Enamel Pins, Fu...",[❤ [Inspiration] Inspired by the Untitled Goos...,<p><b>[Brand]: </b>XVIEONR</p> <p><br></p> <p>...,3413,125.984252
1466187,1987786,Kangroo Sweep Movement Printed Wooden Wall Clo...,"[Dial size: 12 inches in diameter,Big, clear r...",Wall Clocks Are Very Attractive In Looks And E...,1574,1200.000000
1466188,1072666,Skyjacker C7360SP Component Box For PN[C7360PK...,"[Component Box For PN[C7360PK],4 in. Lift,Incl...",Skyjacker C7360SP Component Box For PN[C7360PK...,7367,2000.000000

In [14]:
#checking the remaining missing values

train_data["BULLET_POINTS"] = train_data["BULLET_POINTS"].fillna("")
train_data["DESCRIPTION"] = train_data["DESCRIPTION"].fillna("")

In [15]:
train_data

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,PRODUCT_LENGTH
0,1925202,ArtzFolio Tulip Flowers Blackout Curtain for D...,[LUXURIOUS & APPEALING: Beautiful custom-made ...,,1650,2125.980000
1,2673191,Marks & Spencer Girls' Pyjama Sets T86_2561C_N...,"[Harry Potter Hedwig Pyjamas (6-16 Yrs),100% c...",,2755,393.700000
2,2765088,PRIKNIK Horn Red Electric Air Horn Compressor ...,"[Loud Dual Tone Trumpet Horn, Compatible With ...","Specifications: Color: Red, Material: Aluminiu...",7537,748.031495
3,1594019,ALISHAH Women's Cotton Ankle Length Leggings C...,[Made By 95%cotton and 5% Lycra which gives yo...,AISHAH Women's Lycra Cotton Ankel Leggings. Br...,2996,787.401574
4,2152929,HINS Metal Bucket Shape Plant Pot for Indoor &...,"[Simple and elegant, great for displaying indo...",HINS Brings you the most Elegant Looking Pot w...,5725,950.000000
...,...,...,...,...,...,...
1466184,2690647,Olmeo 14 LED Round Fog Light 4 Inches Waterpro...,"[Easy to install;,Round shape 14LED spot worki...",,7978,590.550000
1466185,2422167,Nike Women's As W Ny Df Swsh Hn Kh Bra (CZ7610...,Material : Polyester,,3009,1181.100000
1466186,2766635,"(3PCS) Goose Game Cute Cartoon Enamel Pins, Fu...",[❤ [Inspiration] Inspired by the Untitled Goos...,<p><b>[Brand]: </b>XVIEONR</p> <p><br></p> <p>...,3413,125.984252
1466187,1987786,Kangroo Sweep Movement Printed Wooden Wall Clo...,"[Dial size: 12 inches in diameter,Big, clear r...",Wall Clocks Are Very Attractive In Looks And E...,1574,1200.000000
1466188,1072666,Skyjacker C7360SP Component Box For PN[C7360PK...,"[Component Box For PN[C7360PK],4 in. Lift,Incl...",Skyjacker C7360SP Component Box For PN[C7360PK...,7367,2000.000000

In [16]:
import re
import unicodedata
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    # Remove HTML tags
    text = re.sub('<[^>]*>', '', text)
    # Remove non-ASCII characters
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8', 'ignore')
    # Remove emojis
    text = re.sub(':[^:]+:', '', text)
    # Remove extra whitespaces
    text = re.sub('\s+', ' ', text).strip()
    # remove stopwords
    text = [word for word in text.split() if word not in stop_words]
    return text

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/onlyaadi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [25]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1466189 entries, 0 to 1466188
Data columns (total 6 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   PRODUCT_ID       1466189 non-null  int64
 1   TITLE            1466189 non-null  object
 2   BULLET_POINTS    1466189 non-null  object
 3   DESCRIPTION      1466189 non-null  object
 4   PRODUCT_TYPE_ID  1466189 non-null  int64
 5   PRODUCT_LENGTH   1466189 non-null  float64
dtypes: float64(1), int64(2), object(3)
memory usage: 67.1+ MB